### ISSUE TITLE
📝 Chore: todo 정리

### ISSUE THREAD

**Issue by kimdoyeonn** [kimdoyeonn/book-note-be#2]
## 설계

- [x] #4

## 기능 구현

- [x] #3
  - [ ] 카카오 소셜 회원가입
  - [ ] 카카오 소셜 로그인
- [ ] Book
  - [x] #6
  - [x] #7
  - [x] #8
  - [x] #9
    - 로그인하지 않은 사용자가 10분간 책의 정보와 노트를 조회할 수 있음
- [ ] #10
  - [ ] 작성 - 저장한 책에 대해 여러 개의 노트를 작성할 수 있음
  - [ ] 조회 - 작성한 본인만 노트를 열람할 수 있음(공유 상태에는 타인도 열람 가능) / 최근 작성한 순으로 정렬
  - [ ] 삭제 - Soft Delete
  - [ ] 수정

## 기타

- [ ] API 테스트 Postman 사용
- [ ] NestJS의 Guard, Interceptor 클래스 활용
- [ ] GraphQL Schema First 방식 사용
- [ ] Jest 테스트 코드 작성
- [ ] AWS 배포
  - [ ] 앱 서버: EC2, ElasticBeanstalk, Fargate 등
  - [ ] DB: RDS free tier 사용
- [ ] Github Action CI/CD 구성
- [ ] Dockerize
